### ISSUE TITLE
/heal (max), /feed, /godmode

### ISSUE THREAD

**Issue by ms5984** [the-h-team/myEssentials#14]
- [ ] Heal
- [x] Feed (fixed by @Allstreamer , thanks!)
- [x] God (fixed)

**Comment by ms5984** [comment]
@Hempfest Status? I can help just not sure where it's at right now

**Comment by ms5984** [comment]
@Hempfest I think these are done; I don't remember, though.

**Comment by Allstreamer** [comment]
/god Seems to stop working when stepping into a "Sweet Berry Bush"
Someone else should definitely try to replicate this

**Comment by ms5984** [comment]
> /god Seems to stop working when stepping into a "Sweet Berry Bush"
> Someone else should definitely try to replicate this

Will do, thanks

**Comment by Allstreamer** [comment]
/god fixed in 9e54c0ad6130fc91ce4441e56d9e3f7ba5a9dc66

Imma build and check if there are any other issues I can find, otherwise I think this is done

**Comment by Allstreamer** [comment]
Seems good to me!
Couldn't find anything

**Comment by ms5984** [comment]
I just updated the task list up top, if /heal is fully functional let's check it off and close this

**Comment by Allstreamer** [comment]
Tested some with /heal
and can't find any more issues, I think this is done now
