### ISSUE TITLE
/god Seems to stop working when stepping into a "Sweet Berry Bush"

### ISSUE THREAD

**Issue by ms5984** [the-h-team/myEssentials#17]
/god Seems to stop working when stepping into a "Sweet Berry Bush"
Someone else should definitely try to replicate this

_Originally posted by @Allstreamer in https://github.com/the-h-team/myEssentials/issues/14#issuecomment-886273109_

**Comment by Allstreamer** [comment]
So it wasn't just my test env

**Comment by ms5984** [comment]
I can't seem to figure out what causes the state flip. I'm going to check and see if the /god state is getting gc'd or something, as I wasn't able to reliably reproduce it with just walking on the bush. I noticed however that whenever I did start taking damage that upon redoing /god it would say "enabled" so my thoughts are just that the state is compromised somehow.

I also died in lava like first thing lol

**Comment by ms5984** [comment]
@Hempfest I think there's a problem with `PlayerSearch` (specifically `PlayerSearch#look(Player)`). At some point i think it returns a fresh object and when that happens it loses the god mode state

**Comment by Hempfest** [comment]
Ill need to do some testing with it, probably a simple bug somewhere data isnt matching so its making a new search instance

**Comment by Allstreamer** [comment]
I looked into it a bit and whenever a player takes damage the Cache gets a new player object.
(Probably a memory leak)

This basically allocates:
- A Sender Object
- A UUID Object ()
- A Invincible boolean (~4 bytes) (Depending on vm)
- A Vanished boolean (~4 bytes) (Depending on vm)
- 36 bytes of overhead
And this for every tick of damage.

(idk the code base to well yet, so idk if this is on purpose)

**Comment by Allstreamer** [comment]
I found out that a new object in the Cache is being created every time PlayerSearch.look() is being called

**Comment by Hempfest** [comment]
Utility problem solved in latest commit.

**Comment by Allstreamer** [comment]
Solved in 9e54c0ad6130fc91ce4441e56d9e3f7ba5a9dc66
